SELECT
    A.BOOK_ID,
    B.AUTHOR_NAME,
    DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK A 
INNER JOIN AUTHOR B
ON A.AUTHOR_ID = B.AUTHOR_ID
AND CATEGORY = '경제'
ORDER BY PUBLISHED_DATE
;